const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='tripsplit_pro_v2';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{user:null,trips:[],currentTrip:null,theme:'light'};
const categories=[
  "Food",
  "Hotel",
  "Transport",
  "Fuel",
  "Flight",
  "Train",
  "Bus",
  "Taxi",
  "Bike Rental",
  "Toll",
  "Parking",
  "Entertainment",
  "Adventure",
  "Shopping",
  "Medical",
  "Emergency",
  "Internet",
  "Laundry",
  "Tips",
  "Insurance",
  "Visa",
  "Miscellaneous",
  "Other"
];
const rates={INR:1,USD:0.012,EUR:0.0105,GBP:0.009, AED:0.044};
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function money(n){const c=state.user?.currency||'INR';return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(n*(rates[c]||1))}
function toast(t){$('#toast').textContent=t;$('#toast').className='show';setTimeout(()=>$('#toast').className='',2200)}
function current(){return state.trips.find(t=>t.id===state.currentTrip)||state.trips[0]}
function initials(n){return (n||'U').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function authInit(){if(state.user) showApp(); else $('#authView').classList.remove('hidden')}
function showApp(){state.currentTrip=state.currentTrip||state.trips[0]?.id;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#welcomeText').textContent=`Hello, ${state.user.name}. Track every rupee of your trip.`;applyTheme();renderAll()}
$('#loginForm').onsubmit=e=>{e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase();const pass=$('#loginPassword').value;if(pass.length<4)return toast('Password must be at least 4 characters');state.user=state.user&&state.user.email===email?state.user:{name:email.split('@')[0],email,currency:'INR'};if(!state.trips.length)createTrip('My First Trip','Chennai',new Date().toISOString().slice(0,10),'',10000);save();showApp()};
$('#registerForm').onsubmit=e=>{e.preventDefault();state.user={name:$('#regName').value.trim(),email:$('#regEmail').value.trim().toLowerCase(),currency:'INR',password:$('#regPassword').value};save();toast('Account created');showLogin()};
$('#forgotForm').onsubmit=e=>{e.preventDefault();if(!state.user||state.user.email!==$('#forgotEmail').value.trim().toLowerCase())return toast('Email not found in this browser');state.user.password=$('#newPassword').value;save();toast('Password reset');showLogin()};
function showLogin(){$('#loginPanel').classList.remove('hidden');$('#registerPanel').classList.add('hidden');$('#forgotPanel').classList.add('hidden')}$('#showRegister').onclick=()=>{$('#loginPanel').classList.add('hidden');$('#registerPanel').classList.remove('hidden')};$('#showForgot').onclick=()=>{$('#loginPanel').classList.add('hidden');$('#forgotPanel').classList.remove('hidden')};$$('.backLogin').forEach(x=>x.onclick=showLogin);
$('#logoutBtn').onclick=()=>{state.user=null;save();location.reload()};
function createTrip(name,destination,start,end,budget){const t={id:Date.now().toString(),name,destination,start,end,budget:Number(budget)||0,members:[{id:crypto.randomUUID(),name:state.user?.name||'You',email:state.user?.email||''}],expenses:[],settlements:[]};state.trips.push(t);state.currentTrip=t.id;save();renderAll();return t}
function tripModal(){openModal(`<h2>Create New Trip</h2><form id="tripForm" class="expense-form"><label>Trip name<input id="tn" required placeholder="Goa Trip"></label><label>Destination<input id="td" placeholder="Goa"></label><label>Start date<input id="ts" type="date"></label><label>End date<input id="te" type="date"></label><label>Budget<input id="tb" type="number" min="0" placeholder="20000"></label><button class="primary">Create Trip</button></form>`);$('#tripForm').onsubmit=e=>{e.preventDefault();createTrip($('#tn').value,$('#td').value,$('#ts').value,$('#te').value,$('#tb').value);closeModal();toast('Trip created')}}
$('#newTripBtn').onclick=tripModal;$('#newTripBtn2').onclick=tripModal;
function expenseModal(existing=null){const t=current();if(!t)return toast('Create a trip first');const ex=existing||{date:new Date().toISOString().slice(0,10),description:'',category:'Food',amount:'',paidBy:t.members[0].id,split:t.members.map(m=>m.id),note:'',receipt:''};openModal(`<h2>${existing?'Edit':'Add'} Expense</h2><form id="expenseForm" class="expense-form"><label>Description<input id="ed" required value="${esc(ex.description)}" placeholder="Dinner"></label><div class="grid2"><label>Amount<input id="ea" type="number" step="0.01" min="0" required value="${ex.amount}"></label><label>Date<input id="edate" type="date" required value="${ex.date}"></label></div><label>Category<select id="ec">${categories.map(c=>`<option ${c===ex.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Paid by<select id="ep">${t.members.map(m=>`<option value="${m.id}" ${m.id===ex.paidBy?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><div><b>Split between</b><div class="split-grid">${t.members.map(m=>`<label class="check"><input type="checkbox" value="${m.id}" ${ex.split.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('')}</div></div><label>Notes<input id="en" value="${esc(ex.note||'')}" placeholder="Optional note"></label><label>Receipt image<input id="er" type="file" accept="image/*"><span class="muted">Stored locally in this browser.</span></label><button class="primary">Save expense</button></form>`);$('#expenseForm').onsubmit=async e=>{e.preventDefault();const ids=$$('#expenseForm input[type=checkbox]:checked').map(x=>x.value);if(!ids.length)return toast('Select at least one person');let receipt=ex.receipt||'';const file=$('#er').files[0];if(file)receipt=await fileToData(file);const obj={id:ex.id||Date.now().toString(),date:$('#edate').value,description:$('#ed').value,category:$('#ec').value,amount:Number($('#ea').value),paidBy:$('#ep').value,split:ids,note:$('#en').value,receipt};if(existing)t.expenses=t.expenses.map(x=>x.id===ex.id?obj:x);else t.expenses.push(obj);save();closeModal();renderAll();toast('Expense saved')}}
function fileToData(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#addExpenseBtn').onclick=()=>expenseModal();$('#addExpenseBtn2').onclick=()=>expenseModal();
function renderAll(){if(!state.user)return;renderTripSelect();renderTrips();renderExpenses();renderMembers();renderSettlements();renderDashboard();renderReport();$('#profileName').value=state.user.name;$('#profileEmail').value=state.user.email;$('#currencySelect').value=state.user.currency||'INR';$('#profileAvatar').textContent=initials(state.user.name);$('#profileBtn').textContent=initials(state.user.name)}
function renderTripSelect(){const sel=$('#tripSelect');sel.innerHTML=state.trips.map(t=>`<option value="${t.id}" ${t.id===state.currentTrip?'selected':''}>${esc(t.name)}${t.destination?' — '+esc(t.destination):''}</option>`).join('');sel.onchange=()=>{state.currentTrip=sel.value;save();renderAll()}}
function renderTrips(){const box=$('#tripCards');box.innerHTML=state.trips.map(t=>`<div class="card trip-card"><h2>${esc(t.name)}</h2><div class="meta">📍 ${esc(t.destination||'No destination')}</div><div class="meta">📅 ${t.start||'—'} → ${t.end||'—'}</div><div class="meta">👥 ${t.members.length} members · 💳 ${t.expenses.length} expenses</div><div class="actions"><button class="primary" onclick="selectTrip('${t.id}')">Open</button><button class="secondary" onclick="editBudget('${t.id}')">Budget</button><button class="danger-outline" onclick="deleteTrip('${t.id}')">Delete</button></div></div>`).join('')||'<div class="card">No trips yet.</div>'}
window.selectTrip=id=>{state.currentTrip=id;save();navigate('dashboard');renderAll()};window.deleteTrip=id=>{if(state.trips.length===1)return toast('Keep at least one trip');if(confirm('Delete this trip and all its expenses?')){state.trips=state.trips.filter(t=>t.id!==id);state.currentTrip=state.trips[0].id;save();renderAll()}};window.editBudget=id=>{const t=state.trips.find(x=>x.id===id);const n=prompt('New trip budget',t.budget);if(n!==null){t.budget=Number(n)||0;save();renderAll()}};
function renderDashboard(){const t=current();if(!t){$('#totalSpent').textContent=money(0);return}const total=t.expenses.reduce((a,e)=>a+e.amount,0);$('#totalSpent').textContent=money(total);$('#budgetValue').textContent=money(t.budget);$('#perPerson').textContent=money(total/Math.max(t.members.length,1));$('#expenseCount').textContent=t.expenses.length;const remain=t.budget-total;$('#budgetRemaining').textContent=remain>=0?`${money(remain)} remaining`:`${money(Math.abs(remain))} over budget`;const pct=t.budget?Math.min(100,total/t.budget*100):0;$('#budgetBar').style.width=pct+'%';$('#budgetText').textContent=t.budget?`${money(total)} of ${money(t.budget)} used (${pct.toFixed(0)}%)`:'No budget set';drawCharts(t);$('#recentExpenses').innerHTML=t.expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(e=>`<div class="recent-row"><span>${esc(e.description)}<small class="muted"> · ${e.category}</small></span><b>${money(e.amount)}</b></div>`).join('')||'<p class="muted">No expenses yet.</p>'}
function drawCharts(t){const cc=$('#categoryChart'),pc=$('#personChart'),ctx=cc.getContext('2d'),pctx=pc.getContext('2d');ctx.clearRect(0,0,cc.width,cc.height);pctx.clearRect(0,0,pc.width,pc.height);const byCat={};categories.forEach(c=>byCat[c]=0);t.expenses.forEach(e=>byCat[e.category]=(byCat[e.category]||0)+e.amount);const vals=Object.entries(byCat).filter(x=>x[1]>0);const total=vals.reduce((a,x)=>a+x[1],0);let ang=-Math.PI/2;vals.forEach(([k,v],i)=>{const a=v/total*Math.PI*2;ctx.beginPath();ctx.moveTo(130,130);ctx.arc(130,130,90,ang,ang+a);ctx.closePath();ctx.fillStyle=`hsl(${230+i*38},70%,${55-i*2}%)`;ctx.fill();ang+=a});ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillText(money(total),130,134);$('#categoryLegend').innerHTML=vals.map(([k,v],i)=>`<span>● ${k}: ${money(v)}</span>`).join('')||'<span>No data</span>';const people=t.members.map(m=>[m.name,t.expenses.filter(e=>e.paidBy===m.id).reduce((a,e)=>a+e.amount,0)]);const max=Math.max(...people.map(x=>x[1]),1);pctx.font='12px system-ui';people.forEach((p,i)=>{const x=20+i*(pc.width/Math.max(people.length,1));const h=p[1]/max*190;pctx.fillStyle=`hsl(${230+i*38},70%,55%)`;pctx.fillRect(x,230-h,Math.max(35,pc.width/Math.max(people.length,1)-20),h);pctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');pctx.save();pctx.translate(x+18,245);pctx.rotate(-.35);pctx.fillText(p[0].slice(0,12),0,0);pctx.restore()})}
function renderExpenses(){const t=current();const filter=$('#categoryFilter');filter.innerHTML='<option value="all">All categories</option>'+categories.map(c=>`<option>${c}</option>`).join('');const search=($('#expenseSearch')?.value||'').toLowerCase(),cat=filter.value;const arr=(t?.expenses||[]).filter(e=>(cat==='all'||e.category===cat)&&(`${e.description} ${e.note}`.toLowerCase().includes(search)));$('#expenseTable').innerHTML=arr.map(e=>{const payer=t.members.find(m=>m.id===e.paidBy)?.name||'?';return `<tr><td>${e.date}</td><td><b>${esc(e.description)}</b>${e.note?`<br><small class="muted">${esc(e.note)}</small>`:''}${e.receipt?`<br><button class="link" onclick="viewReceipt('${e.id}')">Receipt</button>`:''}</td><td><span class="pill">${e.category}</span></td><td>${esc(payer)}</td><td>${e.split.length} people</td><td><b>${money(e.amount)}</b></td><td><button class="link" onclick="editExpense('${e.id}')">Edit</button><button class="link" onclick="deleteExpense('${e.id}')">Delete</button></td></tr>`}).join('')||'<tr><td colspan="7" class="muted">No expenses found.</td></tr>'}
window.editExpense=id=>{const e=current().expenses.find(x=>x.id===id);expenseModal(e)};window.deleteExpense=id=>{if(confirm('Delete this expense?')){const t=current();t.expenses=t.expenses.filter(e=>e.id!==id);save();renderAll();toast('Expense deleted')}};window.viewReceipt=id=>{const e=current().expenses.find(x=>x.id===id);openModal(`<h2>Receipt</h2><img class="receipt-preview" style="max-width:100%;max-height:65vh" src="${e.receipt}" alt="Receipt">`) };
$('#expenseSearch').oninput=renderExpenses;$('#categoryFilter').onchange=renderExpenses;
function renderMembers(){const t=current();$('#memberList').innerHTML=(t?.members||[]).map(m=>`<div class="member-row"><div class="who"><span class="mini-avatar">${initials(m.name)}</span><div><b>${esc(m.name)}</b><small class="muted">${esc(m.email||'')}</small></div></div><button class="danger-outline" onclick="removeMember('${m.id}')">Remove</button></div>`).join('')}
$('#memberForm').onsubmit=e=>{e.preventDefault();const t=current();t.members.push({id:crypto.randomUUID(),name:$('#memberName').value.trim(),email:$('#memberEmail').value.trim()});$('#memberName').value='';$('#memberEmail').value='';save();renderAll();toast('Member added')};window.removeMember=id=>{const t=current();if(t.members.length===1)return toast('A trip needs one member');if(t.expenses.some(e=>e.paidBy===id||e.split.includes(id)))return toast('Cannot remove a member used in expenses');t.members=t.members.filter(m=>m.id!==id);save();renderAll()};
function balances(t){const b={};t.members.forEach(m=>b[m.id]=0);t.expenses.forEach(e=>{b[e.paidBy]+=e.amount;const share=e.amount/e.split.length;e.split.forEach(id=>b[id]-=share)});return b}
function renderSettlements(){const t=current();if(!t){return}const b=balances(t),credit=t.members.filter(m=>b[m.id]>0.005).map(m=>({id:m.id,name:m.name,v:b[m.id]})),debt=t.members.filter(m=>b[m.id]<-0.005).map(m=>({id:m.id,name:m.name,v:-b[m.id]}));const out=[];let i=0,j=0;while(i<debt.length&&j<credit.length){const x=Math.min(debt[i].v,credit[j].v);out.push({from:debt[i].name,to:credit[j].name,amount:x});debt[i].v-=x;credit[j].v-=x;if(debt[i].v<.005)i++;if(credit[j].v<.005)j++}$('#settlementList').innerHTML=out.length?out.map((s,n)=>`<div class="settlement"><span><b>${esc(s.from)}</b> pays <b>${esc(s.to)}</b></span><strong>${money(s.amount)}</strong><button class="secondary" onclick="markPaid(${n},${s.amount},'${esc(s.from)}','${esc(s.to)}')">Mark paid</button></div>`).join(''):'<p class="muted">Everyone is settled 🎉</p>';$('#settlementHistory').innerHTML=(t.settlements||[]).slice().reverse().map(s=>`<div class="recent-row"><span>✓ ${esc(s.from)} paid ${esc(s.to)}</span><b>${money(s.amount)}</b></div>`).join('')||'<p class="muted">No payments recorded.</p>'}
window.markPaid=(n,amount,from,to)=>{const t=current();t.settlements.push({id:Date.now(),from,to,amount,date:new Date().toLocaleDateString()});save();renderSettlements();toast('Settlement recorded')};
function renderReport(){const t=current();if(!t){$('#reportPreview').innerHTML='';return}const total=t.expenses.reduce((a,e)=>a+e.amount,0);const b=balances(t);$('#reportPreview').innerHTML=`<h1>${esc(t.name)}</h1><p><b>Destination:</b> ${esc(t.destination||'—')} &nbsp; <b>Dates:</b> ${t.start||'—'} to ${t.end||'—'}</p><hr><h2>Summary</h2><p>Total: <b>${money(total)}</b> · Budget: <b>${money(t.budget)}</b> · Members: <b>${t.members.length}</b></p><h2>Members & balances</h2><table><thead><tr><th>Member</th><th>Net balance</th></tr></thead><tbody>${t.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${b[m.id]>=0?'+':''}${money(b[m.id])}</td></tr>`).join('')}</tbody></table><h2>Expenses</h2><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Paid by</th><th>Amount</th></tr></thead><tbody>${t.expenses.map(e=>`<tr><td>${e.date}</td><td>${esc(e.description)}</td><td>${e.category}</td><td>${esc(t.members.find(m=>m.id===e.paidBy)?.name||'?')}</td><td>${money(e.amount)}</td></tr>`).join('')}</tbody></table>`}
$('#printReportBtn').onclick=()=>window.print();$('#profileForm').onsubmit=e=>{e.preventDefault();state.user.name=$('#profileName').value.trim();state.user.email=$('#profileEmail').value.trim();state.user.currency=$('#currencySelect').value;save();renderAll();toast('Profile saved')};
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾'}
function exportCsv(){const t=current();if(!t)return;const rows=[['Date','Description','Category','Paid By','Split Members','Amount','Note'],...t.expenses.map(e=>[e.date,e.description,e.category,t.members.find(m=>m.id===e.paidBy)?.name||'',e.split.map(id=>t.members.find(m=>m.id===id)?.name).join('|'),e.amount,e.note||''])];const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${t.name.replace(/\W+/g,'-')}-expenses.csv`;a.click()};$('#exportCsvBtn').onclick=exportCsv;
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden');$('#modalContent').innerHTML=''}$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function navigate(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.section===id))}$$('.nav').forEach(n=>n.onclick=()=>navigate(n.dataset.section));$$('[data-section-jump]').forEach(n=>n.onclick=()=>navigate(n.dataset.sectionJump));$('#profileBtn').onclick=()=>navigate('profile');
authInit();//aunthInit():
window.onload = function () {

    const splashText = document.getElementById("splashText");

    setTimeout(() => {
        splashText.innerHTML = "ST";
    },2000);

    setTimeout(() => {
        splashText.innerHTML = "Split Trip";
    },3000);

    setTimeout(() => {
        document.getElementById("splash").style.display="none";
        document.getElementById("authView").classList.remove("hidden");
        authInit();
    },5000);

};


